package rules;

import com.jin.drools.entity.ao.LevelAo;
import com.jin.drools.entity.dto.ResultDto;

rule "level-A"
    salience 10
    when
        $leveAo : LevelAo(level >= 1 && level <= 5);
        $resultDto : ResultDto();
    then
        $resultDto.setLevel("A");
        insert($resultDto);
     end

rule "level_B"
    when
        $levelAo : LevelAo(level > 5 && level <= 10);
        $resultDto : ResultDto();
    then
        $resultDto.setLevel("B");
        insert($resultDto);
     end
