server:
  port: 8006
spring:
  application:
    name: springboot-activemq

  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      max-connections: 10
      enabled: true
      idle-timeout: 3000

debug: true
logging:
  path: D:/Users/zsxj/logs/
  file: activemq-producer