server:
  port: 9002

spring:
  application:
    name: pointservice
  mvc:
    servlet:
      path: /api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-init-sqls:  set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo2?characterEncodeing=utf8mb4
      username: root
      password: root

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/   #注册到服务注册中心
  #management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: '*'  #监控所有的功能。
  # endpoint:
  #   health:
  #     show-details: always
mybatis:
  mapper-locations:  classpath:mapper/*.xml