server:
  port: 8002
spring:
  application:
    name: springboot-zookeeper
  redis:
    host: 152.136.151.241
    password: qsKopckvo8l^GSFvTpk3VB2tBBwiq7SZ
    port: 7717
    timeout: 30000
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: 20

debug: true
logging:
  path: /Users/zsxj/logs/
  file: springboot-zookeeper