server:
  port: 9001

spring:
  application:
    name: userservice

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-init-sqls:  set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo1?characterEncodeing=utf8mb4
      username: root
      password: root
  mvc:
    servlet:
      path: /api
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      max-connections: 10
      enabled: true
      idle-timeout: 30

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/   #注册到服务注册中心
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'  #监控所有的功能。
 # endpoint:
 #   health:
 #     show-details: always
mybatis:
  mapper-locations:  classpath:mapper/*.xml