server:
  port: 8002
spring:
  application:
    name: pgsql

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-init-sqls:  set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.144.137.185:30006/test?characterEncodeing=utf8mb4
      username: root
      password: root

mybatis:
  mapper-locations:  classpath:mapper/*.xml

debug: true
logging:
  path: D:/Users/zsxj/logs/
  file: springboot-pgsql

